[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
 for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"